//! The two generated files, as strings.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use crate::IconSrc;
use crate::naming::pascal;

pub fn stamp(tag: &str) -> String {
    format!("// GENERATED by typed-lucide/generate from lucide {tag} — do not edit\n")
}

/// A Rust string literal for `s`.
fn lit(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

/// `src/icon.rs`: the enum, the names, the bodies.
pub fn icon_rs(tag: &str, svg_attrs: &str, icons: &[IconSrc]) -> String {
    let count = icons.len();
    let mut out = stamp(tag);

    out.push_str(
        "\n//! Every Lucide icon, its name and its body.\n\
         //!\n\
         //! Regenerate with `cargo run -p generate -- <lucide-tag>`.\n\n",
    );

    out.push_str("/// Every icon in Lucide ");
    out.push_str(tag);
    out.push_str(
        ".\n///\n\
         /// The variant is the icon's kebab name in PascalCase: `arrow-big-right`\n\
         /// is [`Icon::ArrowBigRight`]. [`Display`](core::fmt::Display) gives the\n\
         /// kebab name back.\n\
         #[derive(Copy, Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]\n\
         #[repr(u16)]\n\
         pub enum Icon {\n",
    );
    for icon in icons {
        let _ = writeln!(out, "    /// `{}`", icon.name);
        let _ = writeln!(out, "    {},", pascal(&icon.name));
    }
    out.push_str("}\n\n");

    out.push_str("impl Icon {\n");
    out.push_str("    /// Every icon, sorted by name.\n    pub const ALL: &'static [Icon] = &[\n");
    for icon in icons {
        let _ = writeln!(out, "        Icon::{},", pascal(&icon.name));
    }
    out.push_str("    ];\n\n");
    let _ = writeln!(
        out,
        "    /// How many icons this crate carries: {count}.\n    pub const COUNT: usize = {count};\n"
    );
    out.push_str(
        "    /// The kebab-case Lucide name, e.g. `\"arrow-big-right\"`.\n\
         \x20   pub fn name(self) -> &'static str {\n\
         \x20       NAMES[self as usize]\n\
         \x20   }\n\n\
         \x20   /// The inner SVG elements, for your own `<svg>`.\n\
         \x20   ///\n\
         \x20   /// Lucide's markup with the outer `<svg>` element removed: the\n\
         \x20   /// attributes in Lucide's order, the path data untouched.\n\
         \x20   pub fn body(self) -> &'static str {\n\
         \x20       BODIES[self as usize]\n\
         \x20   }\n\n\
         \x20   /// The icon with this exact kebab name, if Lucide has one.\n\
         \x20   pub fn from_name(name: &str) -> Option<Icon> {\n\
         \x20       NAMES.binary_search(&name).ok().map(|i| Self::ALL[i])\n\
         \x20   }\n\
         }\n\n",
    );

    let _ = writeln!(
        out,
        "/// The `<svg>` attributes every Lucide icon carries, in Lucide's order.\n\
         pub(crate) const SVG_ATTRS: &str = {};\n",
        lit(svg_attrs)
    );

    let _ = writeln!(out, "static NAMES: [&str; {count}] = [");
    for icon in icons {
        let _ = writeln!(out, "    {},", lit(&icon.name));
    }
    out.push_str("];\n\n");

    let _ = writeln!(out, "static BODIES: [&str; {count}] = [");
    for icon in icons {
        let _ = writeln!(out, "    {},", lit(&icon.body));
    }
    out.push_str("];\n");

    out
}

/// `src/meta.rs`: tags, categories, and the search data behind them.
pub fn meta_rs(tag: &str, icons: &[IconSrc]) -> String {
    let count = icons.len();

    let mut categories: BTreeMap<&str, Vec<&str>> = BTreeMap::new();
    let mut tags: BTreeMap<String, Vec<&str>> = BTreeMap::new();
    for icon in icons {
        for c in &icon.categories {
            categories.entry(c).or_default().push(&icon.name);
        }
        for t in &icon.tags {
            tags.entry(t.to_lowercase()).or_default().push(&icon.name);
        }
    }
    let cat_names: Vec<&str> = categories.keys().copied().collect();
    let cat_variant = |name: &str| pascal(name);

    let mut out = stamp(tag);
    out.push_str(
        "\n//! What each icon is for: its tags, its categories, and the text the\n\
         //! search reads.\n\
         //!\n\
         //! Regenerate with `cargo run -p generate -- <lucide-tag>`.\n\n\
         use crate::Icon;\n\n",
    );

    out.push_str("/// Lucide's own categories.\n");
    out.push_str(
        "#[derive(Copy, Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]\n\
         #[repr(u8)]\n\
         pub enum Category {\n",
    );
    for name in &cat_names {
        let _ = writeln!(out, "    /// `{name}`");
        let _ = writeln!(out, "    {},", cat_variant(name));
    }
    out.push_str("}\n\n");

    out.push_str("impl Category {\n");
    out.push_str(
        "    /// Every category, sorted by name.\n    pub const ALL: &'static [Category] = &[\n",
    );
    for name in &cat_names {
        let _ = writeln!(out, "        Category::{},", cat_variant(name));
    }
    out.push_str("    ];\n\n");
    let _ = writeln!(
        out,
        "    /// How many categories Lucide has: {}.\n    pub const COUNT: usize = {};\n",
        cat_names.len(),
        cat_names.len()
    );
    out.push_str(
        "    /// The kebab-case Lucide name, e.g. `\"food-beverage\"`.\n\
         \x20   pub fn name(self) -> &'static str {\n\
         \x20       CATEGORY_NAMES[self as usize]\n\
         \x20   }\n\n\
         \x20   /// Every icon Lucide files under this category, sorted by name.\n\
         \x20   pub fn icons(self) -> &'static [Icon] {\n\
         \x20       CATEGORY_ICONS[self as usize]\n\
         \x20   }\n\n\
         \x20   /// The category with this exact kebab name, if there is one.\n\
         \x20   pub fn from_name(name: &str) -> Option<Category> {\n\
         \x20       CATEGORY_NAMES.binary_search(&name).ok().map(|i| Self::ALL[i])\n\
         \x20   }\n\
         }\n\n",
    );

    let _ = writeln!(
        out,
        "static CATEGORY_NAMES: [&str; {}] = [",
        cat_names.len()
    );
    for name in &cat_names {
        let _ = writeln!(out, "    {},", lit(name));
    }
    out.push_str("];\n\n");

    let _ = writeln!(
        out,
        "static CATEGORY_ICONS: [&[Icon]; {}] = [",
        cat_names.len()
    );
    for name in &cat_names {
        let _ = writeln!(out, "    &[");
        for icon in &categories[name] {
            let _ = writeln!(out, "        Icon::{},", pascal(icon));
        }
        out.push_str("    ],\n");
    }
    out.push_str("];\n\n");

    let _ = writeln!(out, "pub(crate) static TAGS: [&[&str]; {count}] = [");
    for icon in icons {
        let joined = icon
            .tags
            .iter()
            .map(|t| lit(t))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(out, "    &[{joined}],");
    }
    out.push_str("];\n\n");

    let _ = writeln!(
        out,
        "pub(crate) static CATEGORIES: [&[Category]; {count}] = ["
    );
    for icon in icons {
        let joined = icon
            .categories
            .iter()
            .map(|c| format!("Category::{}", cat_variant(c)))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(out, "    &[{joined}],");
    }
    out.push_str("];\n\n");

    out.push_str(
        "/// Name, tags and categories of one icon, lowercased and joined — what a\n\
         /// partial match reads.\n",
    );
    let _ = writeln!(out, "pub(crate) static SEARCH_TEXT: [&str; {count}] = [");
    for icon in icons {
        let mut parts = vec![icon.name.clone()];
        parts.extend(icon.tags.iter().cloned());
        parts.extend(icon.categories.iter().cloned());
        let _ = writeln!(out, "    {},", lit(&parts.join(" ").to_lowercase()));
    }
    out.push_str("];\n\n");

    out.push_str("/// Every tag, lowercased and sorted, with the icons that carry it.\n");
    let _ = writeln!(
        out,
        "pub(crate) static TAG_INDEX: [(&str, &[Icon]); {}] = [",
        tags.len()
    );
    for (tag_name, icon_names) in &tags {
        let joined = icon_names
            .iter()
            .map(|n| format!("Icon::{}", pascal(n)))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(out, "    ({}, &[{joined}]),", lit(tag_name));
    }
    out.push_str("];\n");

    out
}
